### PR TITLE
Swift 3.0 Migration

### PR DESCRIPTION
**Pull request by alexpovh**

### CODE REVIEW

**Comment by ilovezfs** [comment]
ping on this

**Comment by ilovezfs** [comment]
@alexpovh ping on this. I'd really like to get a `dshb` Sierra bottle built for Homebrew as it's one of the remaining five out 4,158 formulae that can't build on 10.12 yet.

**Comment by yn5** [comment]
Seems like a good idea to keep this library a bit up to date by migrating it to the latest version of Swift! @beltex

**Comment by ilovezfs** [comment]
Any updates here @beltex ?

**Comment by beltex** [comment]
Thanks so much for this @alexpovh! So sorry for the super late response folks!

**Pull request merged**
